# Dockerfile personalizado para Jenkins Master
FROM jenkins/jenkins:lts

USER root

# Instalar Docker CLI
RUN apt-get update && apt-get install -y \
    docker.io \
    && rm -rf /var/lib/apt/lists/*

# Copiar lista de plugins
COPY plugins.txt /usr/share/jenkins/ref/plugins.txt

# Instalar plugins
RUN jenkins-plugin-cli --plugin-file /usr/share/jenkins/ref/plugins.txt

# Copiar script de inicialización
COPY jenkins-init.groovy /usr/share/jenkins/ref/init.groovy.d/

# Crear directorio compartido con permisos correctos
RUN mkdir -p /shared && chmod 777 /shared

# Configurar permisos
RUN chown -R jenkins:jenkins /usr/share/jenkins/ref/

USER jenkins